spring:
  application:
    name: api-gateway
    
server:
  port: 2020
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#zuul:
#  routes:
#   doctor-service:
#    path: /rest/**
#    service-id: doctor-service
#    url: http://localhost:8080/doctor-service/
#    strip-prefix: false

management:
  endpoints:
   web:
    exposure:
     include:
      - "*"